default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gymbuddy_development

test:
  <<: *default
  database: gymbuddy_test

production:
  <<: *default
  database: gymbuddy_production
  username: gymbuddy
  password: <%= ENV["POSTGRES_PASSWORD"] %>
